/arm:
  # Publish all joint states-----------------------------------------------------

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Forward Position Controllers ------------------------------------------------------
  J0_positionController:
    type: position_controllers/JointPositionController
    joint: j0

  J1_positionController:
    type: position_controllers/JointPositionController
    joint: j1

  J2_positionController:
    type: position_controllers/JointPositionController
    joint: j2

  J3_positionController:
    type: position_controllers/JointPositionController
    joint: j3
